# Generated by Django 4.1.4 on 2022-12-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(default="0", max_length=13)),
                ("email", models.EmailField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=100)),
                ("favorite", models.BooleanField(default=False)),
                ("group", models.ManyToManyField(blank=True, to="contact.group")),
            ],
        ),
    ]
