# Generated by Django 4.1.4 on 2022-12-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
