# Generated by Django 4.1.4 on 2022-12-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
