# Generated by Django 4.1.4 on 2022-12-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_remove_task_date_task_date_for_complete_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="data_complete",
            new_name="date_complete",
        ),
    ]
