# Generated by Django 4.1.4 on 2022-12-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_rename_data_complete_task_date_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="important",
            field=models.BooleanField(default=False),
        ),
    ]
