# Generated by Django 4.1.4 on 2022-12-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_task_important"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="repeat_daily",
        ),
    ]
